#!/usr/bin/env python3
"""Build patients.md (all five patients on one page) from the patient folders.
Run: python3 make-patients-md.py"""
import csv, re
from pathlib import Path

ROOT = Path(__file__).parent
FOLDERS = ["eczema", "strained-back", "glp1", "persistent-pain", "glaucoma"]


def csv_table(path):
    rows = list(csv.reader(path.open()))
    head, body = rows[0], rows[1:]
    lines = ["| " + " | ".join(head) + " |", "|" + "---|" * len(head)]
    lines += ["| " + " | ".join(r) + " |" for r in body]
    return f"\n**{path.name}**\n\n" + "\n".join(lines) + "\n"


def patient(folder):
    d = ROOT / "patients" / folder
    rel = f"patients/{folder}"
    md = (d / "README.md").read_text().replace("\nLLM-generated file.\n", "")
    md = re.sub(r"\]\(([\w.-]+)\)", rf"]({rel}/\1)", md)
    extras = ""
    for f in sorted(d.iterdir()):
        if f.suffix in (".png", ".jpg"):
            extras += f"\n![{f.name}]({rel}/{f.name})\n"
        elif f.suffix == ".csv":
            extras += csv_table(f)
    return md + extras


header = ("# All five patients\n\n"
          "Generated by `make-patients-md.py` from the folders in `patients/`. Edit those, not this file.\n"
          "Names, dates, messages, and numbers are LLM-generated. Images are real.\n")
(ROOT / "patients.md").write_text("\n---\n\n".join([header] + [patient(f) for f in FOLDERS]))
print("wrote patients.md")
